/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package coyotefeliz;

/**
 *
 * @author Doraly
 */
public class cliente extends javax.swing.JFrame {

    /**
     * Creates new form cliente
     */
    public cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        municipio_cliente = new javax.swing.JComboBox();
        numero_cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombres_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefono_cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        celular_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RFC_cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_cliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        calleynumero_cliente = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        colonia_cliente = new javax.swing.JTextField();
        JLABEL = new javax.swing.JLabel();
        CP_cliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CHECKBOX1 = new java.awt.Checkbox();
        FDA_cliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENTE");
        setBackground(new java.awt.Color(255, 51, 51));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 204, 255));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setName("cliente"); // NOI18N
        setPreferredSize(new java.awt.Dimension(520, 640));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396671_stock_id.png"))); // NOI18N
        jLabel1.setText("No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 97, 43, 20);

        municipio_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        municipio_cliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monterrey", "Guadalupe", "San Nicolás", "Escobedo", "Apodaca", "Juárez", "Cadereyta", "Santiago", "San Pedro", "Santa Catarina" }));
        municipio_cliente.setBorder(null);
        getContentPane().add(municipio_cliente);
        municipio_cliente.setBounds(100, 351, 115, 20);

        numero_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numero_cliente.setBorder(null);
        numero_cliente.setPreferredSize(new java.awt.Dimension(12, 21));
        numero_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(numero_cliente);
        numero_cliente.setBounds(66, 100, 80, 21);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396002_Add-Male-User.png"))); // NOI18N
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 90, 20);

        nombres_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nombres_cliente.setBorder(null);
        getContentPane().add(nombres_cliente);
        nombres_cliente.setBounds(110, 130, 110, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396071_phone-old.png"))); // NOI18N
        jLabel3.setText("Teléfono:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 157, 86, 20);

        telefono_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefono_cliente.setBorder(null);
        telefono_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(telefono_cliente);
        telefono_cliente.setBounds(110, 160, 94, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396798_cellphone.png"))); // NOI18N
        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 157, 74, 20);

        celular_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        celular_cliente.setBorder(null);
        getContentPane().add(celular_cliente);
        celular_cliente.setBounds(290, 161, 120, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396650_Student-id-16.png"))); // NOI18N
        jLabel5.setText("RFC:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 187, 53, 20);

        RFC_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RFC_cliente.setBorder(null);
        getContentPane().add(RFC_cliente);
        RFC_cliente.setBounds(80, 191, 188, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396488_contact_email.png"))); // NOI18N
        jLabel6.setText("Correo Electrónico:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 217, 157, 20);

        email_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email_cliente.setBorder(null);
        getContentPane().add(email_cliente);
        email_cliente.setBounds(180, 221, 230, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395397572_Address_Book_Alt_blue.png"))); // NOI18N
        jLabel7.setText("D I R E C C I Ó N ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 252, 232, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Calle y Número:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 287, 109, 20);

        calleynumero_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        calleynumero_cliente.setBorder(null);
        calleynumero_cliente.setPreferredSize(new java.awt.Dimension(10, 21));
        getContentPane().add(calleynumero_cliente);
        calleynumero_cliente.setBounds(130, 291, 289, 20);

        jlabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlabel.setText("Colonia:");
        getContentPane().add(jlabel);
        jlabel.setBounds(20, 317, 57, 20);

        colonia_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        colonia_cliente.setBorder(null);
        colonia_cliente.setPreferredSize(new java.awt.Dimension(10, 21));
        getContentPane().add(colonia_cliente);
        colonia_cliente.setBounds(80, 321, 191, 20);

        JLABEL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLABEL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        JLABEL.setText("CP:");
        getContentPane().add(JLABEL);
        JLABEL.setBounds(270, 317, 23, 20);

        CP_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CP_cliente.setBorder(null);
        CP_cliente.setPreferredSize(new java.awt.Dimension(10, 21));
        getContentPane().add(CP_cliente);
        CP_cliente.setBounds(300, 321, 114, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Municipio:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 347, 73, 20);

        CHECKBOX1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CHECKBOX1.setLabel("Fuera del A.M.");
        CHECKBOX1.setName(""); // NOI18N
        getContentPane().add(CHECKBOX1);
        CHECKBOX1.setBounds(220, 349, 100, 20);

        FDA_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FDA_cliente.setBorder(null);
        FDA_cliente.setPreferredSize(new java.awt.Dimension(10, 21));
        getContentPane().add(FDA_cliente);
        FDA_cliente.setBounds(330, 351, 88, 20);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395395569_button_cancel.png"))); // NOI18N
        jButton1.setText("Cancelar");
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 535, 103, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396002_Add-Male-User.png"))); // NOI18N
        jButton2.setText("Añadir");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 535, 89, 30);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395397828_back.png"))); // NOI18N
        jButton3.setText("Atrás");
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 535, 83, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Doraly\\Documents\\NetBeansProjects\\coyotefeliz\\src\\coyotefeliz\\imagenes\\1395397202_Client_Male_Light.png")); // NOI18N
        jLabel10.setText("NUEVO CLIENTE");
        jLabel10.setFocusable(false);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 20, 450, 64);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/coyote.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-460, -50, 1000, 680);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coyotefeliz/imagenes/1395396002_Add-Male-User.png"))); // NOI18N
        jLabel12.setText("Nombres:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 127, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_clienteActionPerformed

    private void telefono_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox CHECKBOX1;
    private javax.swing.JTextField CP_cliente;
    private javax.swing.JTextField FDA_cliente;
    private javax.swing.JLabel JLABEL;
    private javax.swing.JTextField RFC_cliente;
    private javax.swing.JTextField calleynumero_cliente;
    private javax.swing.JTextField celular_cliente;
    private javax.swing.JTextField colonia_cliente;
    private javax.swing.JTextField email_cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel;
    private javax.swing.JComboBox municipio_cliente;
    private javax.swing.JTextField nombres_cliente;
    private javax.swing.JTextField numero_cliente;
    private javax.swing.JTextField telefono_cliente;
    // End of variables declaration//GEN-END:variables
}
